--[[
	ScriptFactory - Generates clean, modular Lua scripts from specifications
	Core responsibility: Server scripts, client scripts, modules, UI templates, best practices
]]

local ScriptFactory = {}
local Validator = require(script.Parent.Parent.Utils.Validator)
local UndoManager = require(script.Parent.Parent.Utils.UndoManager)

--[[
	Generate scripts from a specification
]]
function ScriptFactory.generateFromSpec(spec)
	Validator.assertTableKeys(spec, {"name", "type"}, "spec")
	
	local scriptContent = ""
	
	if spec.type == "server" then
		scriptContent = ScriptFactory.generateServerScript(spec)
	elseif spec.type == "client" then
		scriptContent = ScriptFactory.generateClientScript(spec)
	elseif spec.type == "module" then
		scriptContent = ScriptFactory.generateModule(spec)
	elseif spec.type == "ui" then
		scriptContent = ScriptFactory.generateUITemplate(spec)
	end
	
	return {
		name = spec.name,
		type = spec.type,
		content = scriptContent,
		lineCount = select(2, scriptContent:gsub("\n", "\n")) + 1
	}
end

--[[
	Generate a server script with proper structure
]]
function ScriptFactory.generateServerScript(spec)
	local className = spec.name:gsub(" ", "")
	
	return [[
--[[
	]] .. spec.name .. [[ - Server Script
	Auto-generated by ForgeAI
	Created: ]] .. os.date("%Y-%m-%d %H:%M:%S") .. [[
]]
--

local Players = game:GetService("Players")
local RunService = game:GetService("RunService")

-- Services
local ]] .. className .. [[ = {}

-- State
local isRunning = false
local connections = {}

--[[
	Initialize the script
]]
function ]] .. className .. [[:init()
	if isRunning then return end
	isRunning = true
	
	print("[]] .. className .. [[] Initializing server script")
	
	-- Setup event handlers
	self:setupPlayerHandling()
	self:setupGameLoop()
end

--[[
	Handle player connections
]]
function ]] .. className .. [[:setupPlayerHandling()
	table.insert(connections, Players.PlayerAdded:Connect(function(player)
		self:onPlayerAdded(player)
	end))
	
	table.insert(connections, Players.PlayerRemoving:Connect(function(player)
		self:onPlayerRemoving(player)
	end))
	
	-- Handle existing players
	for _, player in ipairs(Players:GetPlayers()) do
		self:onPlayerAdded(player)
	end
end

--[[
	Setup game loop
]]
function ]] .. className .. [[:setupGameLoop()
	local tickRate = 1 / 30 -- 30 FPS update rate
	
	table.insert(connections, RunService.Heartbeat:Connect(function(deltaTime)
		if deltaTime > 0 then
			self:update(deltaTime)
		end
	end))
end

--[[
	Called when player joins
]]
function ]] .. className .. [[:onPlayerAdded(player)
	print("[]] .. className .. [[] Player added: " .. player.Name)
	
	-- Setup player data, characters, etc.
end

--[[
	Called when player leaves
]]
function ]] .. className .. [[:onPlayerRemoving(player)
	print("[]] .. className .. [[] Player leaving: " .. player.Name)
	
	-- Cleanup player data
end

--[[
	Update loop
]]
function ]] .. className .. [[:update(deltaTime)
	-- Game logic goes here
end

--[[
	Cleanup and disconnect
]]
function ]] .. className .. [[:cleanup()
	for _, connection in ipairs(connections) do
		if connection and connection.Connected then
			connection:Disconnect()
		end
	end
	connections = {}
	isRunning = false
end

-- Initialize on script start
]] .. className .. [[:init()

-- Cleanup on script unload
script.Parent:DescendantRemoving:Connect(function(obj)
	if obj == script then
		]] .. className .. [[:cleanup()
	end
end)

return ]] .. className .. [[
]]
end

--[[
	Generate a client script
]]
function ScriptFactory.generateClientScript(spec)
	local className = spec.name:gsub(" ", "")
	
	return [[
--[[
	]] .. spec.name .. [[ - Client Script
	Auto-generated by ForgeAI
	Created: ]] .. os.date("%Y-%m-%d %H:%M:%S") .. [[
]]
--

local UserInputService = game:GetService("UserInputService")
local RunService = game:GetService("RunService")

local ]] .. className .. [[ = {}

-- State
local isRunning = false
local connections = {}

--[[
	Initialize the client script
]]
function ]] .. className .. [[:init()
	if isRunning then return end
	isRunning = true
	
	print("[]] .. className .. [[] Initializing client script")
	
	-- Setup input handling
	self:setupInputHandling()
	
	-- Setup game loop
	self:setupGameLoop()
end

--[[
	Setup input event handling
]]
function ]] .. className .. [[:setupInputHandling()
	table.insert(connections, UserInputService.InputBegan:Connect(function(input, gameProcessed)
		if gameProcessed then return end
		
		self:onInputBegan(input)
	end))
	
	table.insert(connections, UserInputService.InputEnded:Connect(function(input, gameProcessed)
		self:onInputEnded(input)
	end))
end

--[[
	Setup render loop
]]
function ]] .. className .. [[:setupGameLoop()
	table.insert(connections, RunService.RenderStepped:Connect(function(deltaTime)
		self:update(deltaTime)
	end))
end

--[[
	Handle input began
]]
function ]] .. className .. [[:onInputBegan(input)
	if input.UserInputType == Enum.UserInputType.Keyboard then
		print("[]] .. className .. [[] Key pressed: " .. tostring(input.KeyCode))
	end
end

--[[
	Handle input ended
]]
function ]] .. className .. [[:onInputEnded(input)
	if input.UserInputType == Enum.UserInputType.Keyboard then
		print("[]] .. className .. [[] Key released: " .. tostring(input.KeyCode))
	end
end

--[[
	Render/update loop
]]
function ]] .. className .. [[:update(deltaTime)
	-- Client-side logic goes here
end

--[[
	Cleanup
]]
function ]] .. className .. [[:cleanup()
	for _, connection in ipairs(connections) do
		if connection and connection.Connected then
			connection:Disconnect()
		end
	end
	connections = {}
	isRunning = false
end

-- Initialize
]] .. className .. [[:init()

return ]] .. className .. [[
]]
end

--[[
	Generate a module script
]]
function ScriptFactory.generateModule(spec)
	local moduleName = spec.name:gsub(" ", "")
	
	return [[
--[[
	]] .. spec.name .. [[ - Module
	Auto-generated by ForgeAI
	Created: ]] .. os.date("%Y-%m-%d %H:%M:%S") .. [[
]]
--

local ]] .. moduleName .. [[ = {}

--[[
	Initialize module
]]
function ]] .. moduleName .. [[:new()
	local self = setmetatable({}, {__index = ]] .. moduleName .. [[})
	
	return self
end

--[[
	Example method
]]
function ]] .. moduleName .. [[:getValue()
	return "Hello from " .. self.__class
end

return ]] .. moduleName .. [[
]]
end

--[[
	Generate UI template
]]
function ScriptFactory.generateUITemplate(spec)
	return [[
--[[
	]] .. spec.name .. [[ - UI Template
	Auto-generated by ForgeAI
	Created: ]] .. os.date("%Y-%m-%d %H:%M:%S") .. [[
]]
--

local UIModule = {}

--[[
	Create UI from template
]]
function UIModule.createUI(parent)
	-- Main container
	local frame = Instance.new("Frame")
	frame.Name = "MainUI"
	frame.Size = UDim2.new(1, 0, 1, 0)
	frame.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
	frame.BorderSizePixel = 0
	frame.Parent = parent
	
	-- Title bar
	local titleBar = Instance.new("TextLabel")
	titleBar.Name = "TitleBar"
	titleBar.Size = UDim2.new(1, 0, 0, 40)
	titleBar.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
	titleBar.TextColor3 = Color3.fromRGB(255, 255, 255)
	titleBar.Text = "]] .. spec.name .. [["
	titleBar.TextSize = 14
	titleBar.Font = Enum.Font.GothamBold
	titleBar.Parent = frame
	
	-- Content area
	local contentArea = Instance.new("ScrollingFrame")
	contentArea.Name = "ContentArea"
	contentArea.Size = UDim2.new(1, 0, 1, -40)
	contentArea.Position = UDim2.new(0, 0, 0, 40)
	contentArea.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
	contentArea.BorderSizePixel = 0
	contentArea.ScrollBarThickness = 8
	contentArea.Parent = frame
	
	return frame
end

return UIModule
]]
end

--[[
	Get template suggestions for a framework
]]
function ScriptFactory.getFrameworkTemplate(framework)
	local templates = {
		OOP = {
			pattern = "class",
			inheritance = true,
			example = "local MyClass = {} function MyClass:new() end"
		},
		FSM = {
			pattern = "state_machine",
			states = {"idle", "running", "paused"},
			example = "local states = {idle = {}, running = {}}"
		}
	}
	
	return templates[framework] or templates.OOP
end

return ScriptFactory
